services:
  app:
    build: .
    container_name: spring_app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy  # Chờ cho đến khi db báo "healthy"
    env_file:
      - .env.local # tên file biến môi trường
    restart: unless-stopped

  db:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    # Quan trọng: Healthcheck giúp Docker biết khi nào MySQL thực sự sẵn sàng
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p123456"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mysql_data: