spring.application.name=SOCIAL_MEDIA_BE
server.port=${PORT:8080}
spring.profiles.active=dev
# db
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
# JPA/Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=true
# File Upload Configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
# jwt
jwt.secret=${JWT_SECRET}
jwt.expiration=900000
jwt.refresh-expiration=604800000
#cloudinary
CLOUDINARY_URL=${CLOUDINARY_URL}
#avatar default
app.avatar.default-url=${AVATAR_DEFAULT_URL}

# OAuth2 Google
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri=${BASE_URL}/login/oauth2/callback/google

# OAuth2 Facebook
spring.security.oauth2.client.registration.facebook.client-id=${FACEBOOK_CLIENT_ID}
spring.security.oauth2.client.registration.facebook.client-secret=${FACEBOOK_SECRET}
spring.security.oauth2.client.registration.facebook.scope=email,public_profile
spring.security.oauth2.client.registration.facebook.redirect-uri=${BASE_URL}/login/oauth2/callback/facebook

# Frontend URL (cho CORS vÃ  redirect)
app.frontend-url=https://localhost:3000
app.oauth2.authorized-redirect-uris=https://localhost:3000/oauth2/redirect

# Server SSL (Configured in .env.local for Docker) (hide for production)
# server.ssl.key-store=classpath:keystore.p12
# server.ssl.key-store-password=123456
# server.ssl.key-store-type=PKCS12

# spam / bot detection
spam.comment.rate-limit.max-per-window=5
spam.comment.rate-limit.window-seconds=30
register.suspectIp.threshold=3
register.suspectIp.windowHours=24

# Content moderation blacklist
app.content-moderation.forbidden-keywords=sex,porn,xxx,hentai,viagra,đồi trụy,bao cao su
app.content-moderation.forbidden-patterns=sex|porn|hentai|viagra|đồi trụy|bao cao su
